#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-bones
Version  : 3.8.3
Release  : 5
URL      : https://rubygems.org/downloads/bones-3.8.3.gem
Source0  : https://rubygems.org/downloads/bones-3.8.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-bones-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
Mr Bones
by Tim Pease
https://rubygems.org/gems/bones
== DESCRIPTION:
Mr Bones is a handy tool that creates new Ruby projects from a code
skeleton. The skeleton contains some starter code and a collection of rake
tasks to ease the management and deployment of your source code. Several Mr
Bones plugins are available for creating git repositories, creating GitHub
projects, running various test suites and source code analysis tools.

%package bin
Summary: bin components for the rubygem-bones package.
Group: Binaries

%description bin
bin components for the rubygem-bones package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n bones-3.8.3
gem spec %{SOURCE0} -l --ruby > rubygem-bones.gemspec

%build
gem build rubygem-bones.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
bones-3.8.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/bones-3.8.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/History.txt
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/bin/bones
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/default/.bnsignore
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/default/History.txt.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/default/README.md.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/default/Rakefile.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/default/bin/NAME.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/default/lib/NAME.rb.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/default/spec/NAME_spec.rb.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/default/spec/spec_helper.rb.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/default/test/test_NAME.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/default/version.txt
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/annotation_extractor.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/app.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/app/command.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/app/create.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/app/file_manager.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/app/freeze.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/app/info.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/app/plugins.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/app/unfreeze.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/colors.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/gem_package_task.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/plugins/ann.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/plugins/bones_plugin.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/plugins/gem.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/plugins/notes.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/plugins/rdoc.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/plugins/test.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/lib/bones/rake_override_task.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/script/bootstrap
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/bones/app/file_manager_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/bones/app_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/bones/helpers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/bones_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/data/default/.bnsignore
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/data/default/.rvmrc.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/data/default/History
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/data/default/NAME/NAME.rb.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/data/default/README.md.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/data/default/Rakefile.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/data/default/bin/NAME.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/data/default/lib/NAME.rb.bns
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/data/foo/README.md
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/data/foo/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/data/markdown.txt
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/data/rdoc.txt
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/bones-3.8.3/version.txt
/usr/lib64/ruby/gems/2.3.0/specifications/bones-3.8.3.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/bones
